### ISSUE TITLE
Use PATH to find executables by default

### ISSUE THREAD

**Issue by paulmillar** [alrossi/xrootd-tpc-utils#1]
The test suite uses `xrdcp` and `xrdfs` executables, but requires the user to configure their location.

While being able to specify an install path for these executables is certainly a useful feature, I imagine in most cases people will have that directory in their `PATH` environment variable.  This means that simply invoking `xrdcp` and `xrdfs` should just work.

It would be nice if the test suite used `PATH`; for example, by building a command-line with just the executable name (no path) if "xrootd-setting" / "home" configuration isn't specified.

**Comment by alrossi** [comment]
I did it this way of course so that I could test various versions of the client without having to install and uninstall them into /usr/bin.  

But the option not to specify should be easy enough to do.   There is a validation check, however, which would have to be skipped, where I make sure the specified binary file actually does exist.

**Comment by alrossi** [comment]
Done.
