### ISSUE TITLE
Check if user has valid voms proxy before starting tests

### ISSUE THREAD

**Issue by paulmillar** [alrossi/xrootd-tpc-utils#2]
The test suite heavily depends on X.509 for authentication.  Without a valid X.509 credential, all tests will fail.

It would be helpful if the tests did a pre-flight check, verifying that the user has a valid proxy, ideally also checking that the credential also asserts dteam membership.  This would avoid running the tests mistakenly without a proxy.

**Comment by alrossi** [comment]
I would think that if we are going to do this, then I would need to include the option of whether to use voms-proxy-info or grid-proxy-info, since this suite is not limited to dteam testing.

Lacking the info executable in the path fails the test suite.

I guess I just have to parse the output line by line to find fqan and expiration ...

**Comment by alrossi** [comment]
Done
